"""remove col table tokens

Revision ID: f279c861e6f0
Revises: 57f94287c28b
Create Date: 2025-09-19 12:55:48.128601

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f279c861e6f0"
down_revision: str | Sequence[str] | None = "57f94287c28b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token", "is_revoked")
    op.drop_column("token", "expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "token", sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False)
    )
    op.add_column("token", sa.Column("is_revoked", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
